// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_JVROJerI-OUdC8-qCmQsd5VEC3mg3n4',
    appId: '1:364096947529:web:102684839a750295ca0698',
    messagingSenderId: '364096947529',
    projectId: 'flutterchatpro-9430f',
    authDomain: 'flutterchatpro-9430f.firebaseapp.com',
    storageBucket: 'flutterchatpro-9430f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMp33WNs3mVnnd7DDe5XqZr9rfianSHjY',
    appId: '1:364096947529:android:2780ca23c507b897ca0698',
    messagingSenderId: '364096947529',
    projectId: 'flutterchatpro-9430f',
    storageBucket: 'flutterchatpro-9430f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfGSOhC35C4ChIpJKBerA8pSPamXRwjWc',
    appId: '1:364096947529:ios:4a8d83d87c4fd75eca0698',
    messagingSenderId: '364096947529',
    projectId: 'flutterchatpro-9430f',
    storageBucket: 'flutterchatpro-9430f.appspot.com',
    iosBundleId: 'com.pvh.flutterchatpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_JVROJerI-OUdC8-qCmQsd5VEC3mg3n4',
    appId: '1:364096947529:web:61045570a32ee8adca0698',
    messagingSenderId: '364096947529',
    projectId: 'flutterchatpro-9430f',
    authDomain: 'flutterchatpro-9430f.firebaseapp.com',
    storageBucket: 'flutterchatpro-9430f.appspot.com',
  );
}
